### ISSUE TITLE
Lorraine Metz needs an account to use our S3 and Sandbox for SPARROW data processing

### ISSUE THREAD

**Issue by esmyers** [USGS-WiM/sparrow-national-dissolved-solids-js#77]
She'll be doing some data processing and publishing on our SparrowTest instance using the jump server.  I'm not sure she needs access to production, but I don't think it's bad if she has it either.  It would be up to your discretion and access policy

**Comment by aaronstephenson** [comment]
I created an IAM account for her, with read/write access to the sparrow website S3 bucket and start/stop permissions on the AGSJump1051 server, as well as a WIMCLOUDAD account so that she can RDP onto the jump server. I'm assuming you'll show her the ropes on how to install and use the AWS CLI and RDC, but I'm happy to help if you'd like.

**Comment by esmyers** [comment]
would  you like me to share my AWS access/secret access keys with her or have you sent them to her already?

**Comment by aaronstephenson** [comment]
No, those are for you only. I sent her ones created specifically for her.
